{% set name = "csp-adapter-symphony" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/csp-adapter-symphony/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a75dd580306810f4dadb73cf359fad5eb75c9a6657bf7f3c5a8bdec53b93f2b6

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - csp
    - requests
    - tenacity

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - csp_adapter_symphony

about:
  home: http://github.com/point72/csp-adapter-symphony
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A csp adapter for symphony
  description: A csp adapter for symphony
  dev_url: http://github.com/point72/csp-adapter-symphony

extra:
  recipe-maintainers:
    - timkpaine
