{% set name = "csp-adapter-symphony" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/csp-adapter-symphony/csp_adapter_symphony-{{ version }}.post2.tar.gz
  sha256: ff3702aa3d9e0e43ccdf68595d281f4b43657be34fb40c37913d863c6003acbd

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - csp
    - requests

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - csp_adapter_symphony

about:
  home: http://github.com/point72/csp-adapter-symphony
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A csp adapter for symphony
  description: A csp adapter for symphony
  dev_url: http://github.com/point72/csp-adapter-symphony

extra:
  recipe-maintainers:
    - timkpaine
